server:
  type: default
  maxThreads: 100000
  requestLog:
    appenders:
      - type: file
        currentLogFilename: /var/log/faiyah/service-auth.log
        archive: false
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001
