server:
  type: default
  maxThreads: 100000
  requestLog:
    appenders:
      - type: file
        currentLogFilename: /var/log/faiyah/service-auth.log
        archive: false
  applicationConnectors:
    - type: http
      port: 9000
    - type: https
      port: 443
      keyStorePath: ./keystore.jks
      keyStorePassword: NotSoSmartFox
      validateCerts: false
      validatePeers: false
  adminConnectors:
    - type: http
      port: 9001